Obscenity.configure do |config|
  config.blacklist = [
    'film',
    'filmisnotdead',
    'hipster',
    'fact',
    'geek',
    'trivia',
    'sad',
    'feelings',
    'depressing thoughts',
    'my art',
    'madewithpaper',
    'fiftythree',
    'birthday',
    'grunge',
    'pale',
    'pixar',
    'disney',
    'vape',
    'feminism',
    'grafitti',
    'nick cannon',
    'blood',
    'nikon',
    'canon',
    'iphone',
    'sewing',
    'crafts',
    'pokemon',
    'housing',
    'estate',
    'sunset',
    'boobs',
    'ass',
    'finger',
    'skate',
    'stock photos',
    'cat',
    'photographers on tumblr',
    'cloud',
    'garage',
    'dance',
    'grundtvig'
  ]
end
